name: Deploy to Server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH config
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST }}
    - name: SSH connection to Server
      run: ssh -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} /home/villwulf/project/external/startup.sh zkapi
